## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache/files

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - cp config/sr-config.example.php config/sr-config.php
  - composer install

language: php
php:
  - '7.3'

script:
  - ./bin/slim-rbac migrate -c config/sr-config.php
  - vendor/bin/codecept  run --coverage --coverage-xml
  - cp tests/_output/coverage.xml ./coverage.xml
  - cp tests/_output/coverage.serialized ./coverage.serialized

after_success:
    - bash <(curl -s https://codecov.io/bash)
  
