rbac:
  userId:
    fieldName: userId
    resourceType: attribute
  database:
    driver: pdo_mysql
    host: 127.0.0.1
    user: root
    password: password
    port: 3306
    dbname: db
    charset: utf8
