<?php

namespace Potievdev\SlimRbac\Models\Repository;

use Doctrine\ORM\EntityRepository;
use Potievdev\SlimRbac\Models\Entity\Permission;

/**
 * RolePermissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolePermissionRepository extends EntityRepository
{
    /**
     * @param Permission $permission
     * @return array
     */
    public function getRoleIdsByPermission(Permission $permission)
    {
        $qb = $this->createQueryBuilder('rolePermission');

        $qb->select('rolePermission.role_id')
            ->where($qb->expr()->eq('rolePermission.permission_id', $permission->getId()));

        return $qb->getQuery()->getArrayResult();
    }
}
