<?php

namespace Potievdev\SlimRbac\Models\Repository;

use Doctrine\ORM\EntityRepository;
use Potievdev\SlimRbac\Models\Entity\Permission;

/**
 * RolePermissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolePermissionRepository extends EntityRepository
{
    /**
     * @param Permission $permission
     * @return array
     */
    public function getRoleIdsByPermission(Permission $permission)
    {
        $qb = $this->createQueryBuilder('rolePermission');

        $qb->select('rolePermission.roleId')
            ->where($qb->expr()->eq('rolePermission.permissionId', $permission->getId()));

        return $qb->getQuery()->getArrayResult();
    }

    /**
     * Search RolePermission record. If found return true else false
     * @param integer $permissionId
     * @param integer[] $roleIds
     * @return bool
     */
    public function isPermissionAssigned($permissionId, $roleIds)
    {
        $qb = $this->createQueryBuilder('rolePermission');

        $result = $qb
            ->select('rolePermission.id')
            ->where(
                $qb->expr()->andX(
                    $qb->expr()->eq('rolePermission.permissionId', $permissionId),
                    $qb->expr()->in('rolePermission.roleId', $roleIds)
                )
            )
            ->setMaxResults(1)
            ->getQuery()
            ->getArrayResult();

        return count($result) > 0;
    }
}
