<?php

namespace Potievdev\SlimRbac\Models\Repository;

use Doctrine\ORM\EntityRepository;
use Potievdev\SlimRbac\Helper\ArrayHelper;

/**
 * UserRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleHierarchyRepository extends EntityRepository
{
    /**
     * Returns array of child role ids for given parent role ids
     * @param integer[] $parentIds
     * @return integer[]
     */
    private function getChildIds($parentIds)
    {
        $qb = $this->createQueryBuilder('roleHierarchy');

        $qb->select('roleHierarchy.childRoleId')
            ->where($qb->expr()->in( 'roleHierarchy.parentRoleId', $parentIds))
            ->indexBy('roleHierarchy', 'roleHierarchy.childRoleId');

        $childRoleIds =  $qb->getQuery()->getArrayResult();

        return array_keys($childRoleIds);
    }

    /**
     * Returns all child role ids for given parent role ids
     * @param integer[] $parentIds
     * @return integer[]
     */
    private function getAllChildRoleIds($parentIds)
    {
        $allChildIds = [];

        do {
            $parentIds = $this->getChildIds($parentIds);
            $allChildIds = ArrayHelper::merge($allChildIds, $parentIds);
        } while (count($parentIds) > 0);

        return $allChildIds;
    }

    /**
     * @param integer[] $rootRoleIds
     * @return integer[]
     */
    public function getAllRoleIdsHierarchy($rootRoleIds)
    {
        $childRoleIds = $this->getAllChildRoleIds($rootRoleIds);

        return ArrayHelper::merge($rootRoleIds, $childRoleIds);
    }
}