<?php

namespace Potievdev\SlimRbac\Models\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRoleRepository extends EntityRepository
{
    /**
     * @param integer $userId
     * @return array
     * @throws \Doctrine\ORM\Query\QueryException
     */
    public function getUserRoleIds($userId)
    {
        $qb = $this->createQueryBuilder('userRole');

        $qb->select('userRole.roleId')
            ->where($qb->expr()->eq('userRole.userId', $userId))
        ->indexBy('userRole', 'userRole.roleId');

        $roleIds = $qb->getQuery()->getArrayResult();

        return array_keys($roleIds);
    }
}
